### ISSUE TITLE
Get-CPrivilege doesn't work any more?

### ISSUE THREAD

**Issue by DennisL68** [webmd-health-services/Carbon.Security#6]
It's been a while since I used this command, but when I tried it today (with both a domain account and a local account), there is no output anymore.

~~~
Get-CPrivilege -Identity <account>
~~~

**Comment by splatteredbits** [comment]
Then most likely the account doesn't have any privileges.

**Comment by DennisL68** [comment]
It's admin accounts, and `whoami /priv` do display an amount of available privileges.

**Comment by splatteredbits** [comment]
Are you running in an administrator PowerShell console session?

**Comment by splatteredbits** [comment]
Hmm. Carbon.Security seems to give a different answer than `whoami /priv` . Both `Get-CPrivilege` in this module and the original in Carbon.

![image](https://github.com/user-attachments/assets/9e054e80-6e85-4437-bde6-5a1c5c1276ad)

**Comment by DennisL68** [comment]
`whoami`, for one, has never been able to show `LogonAsBatchJob`.

`Get-CPrivilege` should be the more complete one.

And I've tried running as both admin and not.

**Comment by splatteredbits** [comment]
It looks like `whoami /priv` is showing some privileges that user has that are somehow implicitly granted? If I use `Grant-CPrivilege` to grant a privilege that `whoami /priv` shows I have, then `Get-CPrivilege` starts returning it as one of my privileges:

![image](https://github.com/user-attachments/assets/1eb11abe-835a-4e76-8603-3d0e1582b801)

**Comment by DennisL68** [comment]
I'm pretty sure (but can't remember), that `Get-CPrivilege` did show the effective privileges before.

**Comment by splatteredbits** [comment]
We haven't changed the underlying Win32 API that `Get-CPrivilege` uses to enumerate an account's privileges.

* Carbon: https://github.com/webmd-health-services/Carbon/blob/main/Source/Security/Privilege.cs#L165
* Carbon.Security: https://github.com/webmd-health-services/Carbon/blob/main/Source/Security/Privilege.cs#L165, which calls https://github.com/webmd-health-services/PureInvoke/blob/main/PureInvoke/Functions/Invoke-AdvApiLsaEnumerateAccountRights.ps1#L45 .

`Get-CPrivilege` has only ever listed an account's explicit privileges. If the account gets a privilege from a security group, `Get-CPrivilege` won't show those rights. It looks like that is what `whoami /priv` does: it also goes through all an account's groups and checks privileges granted through those groups. Perhaps that is what is going on here? The privilege you expect is being granted to a group the user is in and not the user itself?

**Comment by DennisL68** [comment]
Yes, that must be it.

Thx for the clarification. Perhaps the help text could be updated to clarify that only explicit permissions are shown?

**Comment by splatteredbits** [comment]
Looks like privileges can be in three states: not granted, granted and enabled, and granted and disabled. `whoami /priv` will show all granted privileges *and* whether they are enabled/disabled or not. The Win32 API `LsaEnumerateAccountRights` method reports only granted privileges, regardless if they are enabled/disabled, so that is what `Get-CPrivilege` shows.

I'm not sure how we would detect if a privilege is enabled/disabled.

Source: https://superuser.com/questions/1254253/how-am-i-able-to-shutdown-the-system-when-i-dont-have-seshutdownprivilege

**Comment by splatteredbits** [comment]
> Yes, that must be it.
> 
> Thx for the clarification. Perhaps the help text could be updated to clarify that only explicit permissions are shown?

Yes. This is a good idea.

**Comment by splatteredbits** [comment]
Carbon.Security 1.0.3 is out and contains this documentation.
